name: Continuous integration
on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'bugfix/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/routes/gameRouter.js.html
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Run ESlint
        run: npm run lint